#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Fri Sep 11 11:25:51 2026

add_design "C:/Users/Admin/Workspace/DIC-demo/helloworld/source/Test.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Test
add_design "C:/Users/Admin/Workspace/DIC-demo/helloworld/source/tb_Test.v"
add_simulation "C:/Users/Admin/Workspace/DIC-demo/helloworld/source/tb_Test.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Test
synthesize -ads -selected_syn_tool_opt 2 
remove_design -verilog "C:/Users/Admin/Workspace/DIC-demo/helloworld/source/tb_Test.v"
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Test
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
