#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Fri Sep 18 11:49:24 2026

add_design "C:/Users/Admin/Workspace/DIC-demo/lab/source/Lab2_Task1.v"
add_simulation "C:/Users/Admin/Workspace/DIC-demo/lab/source/tb_Lab2_Task1.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Lab2_Task1
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Lab2_Task1
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Lab2_Task1
synthesize -ads -selected_syn_tool_opt 2 
add_design "C:/Users/Admin/Workspace/DIC-demo/lab/source/Lab2_Task2.v"
add_simulation "C:/Users/Admin/Workspace/DIC-demo/lab/source/tb_Lab2_Task2.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Lab2_Task1
synthesize -ads -selected_syn_tool_opt 2 
remove_design -verilog "C:/Users/Admin/Workspace/DIC-demo/lab/source/Lab2_Task2.v"
add_design "C:/Users/Admin/Workspace/DIC-demo/lab/source/Lab2_Task2.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Lab2_Task2
add_design "C:/Users/Admin/Workspace/DIC-demo/lab/source/Lab2_Task3.v"
add_simulation "C:/Users/Admin/Workspace/DIC-demo/lab/source/tb_Lab2_Task3.v"
add_design "C:/Users/Admin/Workspace/DIC-demo/lab/source/Lab2_Task4.v"
add_simulation "C:/Users/Admin/Workspace/DIC-demo/lab/source/tb_Lab2_Task4.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Lab2_Task1
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module Lab2_Task1
synthesize -ads -selected_syn_tool_opt 2 
